config/routes.rb
Rails.application.routes.draw do
  #管理者用
  # URL /customers/sign_in...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
   get 'searches/search'

  namespace :admin do
   root to: "homes#top"
   get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
   resources :items, only: [:index, :show, :new, :create, :edit, :update]
   resources :genres, only: [:index, :edit, :create, :update]
   resources :orders, only: [:show, :update]
   resources :order_details, only: [:update]
   resources :customers, only: [:index, :show, :edit, :update]
  end

 #顧客用
  devise_for :customers, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/quit' => 'customers#quit', as: 'confirm_quit'
    put 'customers/information' => 'customers#update'
    patch 'customers/out' => 'customers#out', as: 'out_customer'
    get 'about',to: 'homes#about'
    get '/genre/:id' =>'homes#index', as: 'index'
    resources :items, only: [:index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :orders, only:[:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end




  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy

  scope :only_active, -> { where(is_deleted: false) }


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/ }


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  # 氏名をまとめたメソッド
  def customer_name
    last_name + first_name
  end

    def self.looks(search, word)
      @customers = Customer.where("first_name LIKE? OR last_name LIKE? OR first_name_kana LIKE? OR last_name_kana LIKE? OR phone_number LIKE? OR address LIKE? OR email LIKE?",
      "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%")
    end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = "会員情報を変更に成功しました。"
      redirect_to admin_customer_path(@customer.id)
    else 
      flash.now[:danger] = "会員情報の変更ができませんでした。"
      render :edit
    end
  end
  
  
  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="title pt-4">
      <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
    </div>
  </div>
  <div>
    <%= flash[:alert] %>
  </div>
  <div class="row">
    <div class="col-12">
      <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
      <table class="table table-borderless">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= f.text_field :last_name, class: "form-control" %></td>
          <td><%= f.text_field :first_name, class: "form-control" %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= f.text_field :last_name_kana, class: "form-control" %></td>
          <td><%= f.text_field :first_name_kana, class: "form-control" %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= f.text_field :postal_code, class: "form-control" %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= f.text_field :address, class: "form-control" %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <th><%= f.text_field :phone_number, class: "form-control" %></th>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= f.text_field :email, class: "form-control" %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :有効 %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :退会 %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row pt-5 pl-5 ml-5">
    <div class="customer-group">
      <div class="title">
        <h3 class="text-center bg-light">会員一覧</h3>
      </div>
    </div>
  </div>
    <div class="row pt-5 justify-content-center">
      <div class="col-9">
        <table class="table">
          <thead class="bg-light text-center">
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
          <% @customers.each do |customer| %>
            <tr class="text-center">
              <td><%= customer.id %></td>
              <td>
              <%= link_to admin_customer_path(customer.id) do %>
              <%= "#{customer.last_name}#{customer.first_name}" %>
              <% end %>
              </td>
              <td><%= customer.email %></td>
              <% if customer.is_deleted == false %>
                <td class="text-success">有効</td>
              <% else %>
                <td class="text-secondary">退会</td>
              <% end %>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="pagination d-flex justify-content-center mb-4">
      <%= paginate @customers %>
    </div>
</div>
  

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row pt-5">
    <div class="title pt-4 ml-5">
      <h3 class="text-center bg-light"><%= "#{@customer.last_name}#{@customer.first_name}さんの会員情報" %></h3>
    </div>
  </div>
  <div class="row pl-5">
    <div class="col-8">
    <table class="table table-borderless">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @customer.last_name %><%= @customer.first_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <% if @customer.is_deleted == false %>
          <td class="text-success">有効</td>
        <% else %>
          <td class="text-secondary">退会</td>
        <% end %>
      </tr>
    </table>
    </div>
  </div>
  <div class="text-center">
        <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
        <%= link_to "注文履歴一覧を見る", admin_order_path(@customer.id), class: "btn btn-primary" %>
  </div>
</div>