config/routes.rb
Rails.application.routes.draw do
  #管理者用
  # URL /customers/sign_in...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
   get 'searches/search'

  namespace :admin do
   root to: "homes#top"
   get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
   resources :items, only: [:index, :show, :new, :create, :edit, :update]
   resources :genres, only: [:index, :edit, :create, :update]
   resources :orders, only: [:show, :update]
   resources :order_details, only: [:update]
   resources :customers, only: [:index, :show, :edit, :update]
  end

 #顧客用
  devise_for :customers, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/quit' => 'customers#quit', as: 'confirm_quit'
    put 'customers/information' => 'customers#update'
    patch 'customers/out' => 'customers#out', as: 'out_customer'
    get 'about',to: 'homes#about'
    get '/genre/:id' =>'homes#index', as: 'index'
    resources :items, only: [:index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :orders, only:[:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end




  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit:0, bank: 1}
  enum order_status: {wait: 0, check: 1, making: 2, standby: 3, sent:4}

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postage, presence: true
  # セレクトボタン内に1行でまとめて表示させるメソッド
  def address_display
    '〒' + postal_code + ' '+ address1 + ' ' + name
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).reverse_order
    elsif params[:created_at] == "today"
      @orders = Order.ordered_today.includes(:customer).page(params[:page]).reverse_order
    else
      @orders = Order.includes(:customer).page(params[:page]).reverse_order
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @product_total = @order_details.inject(0) { |sum, order_detail| sum + order_detail.total_price }
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.order_status == "check"
    end
      redirect_to admin_order_path
  end


  private
  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/views/admin/orders/index.html.erb
<section class="inner">
 <h4>
  <% if params[:customer_id] %>
    <%= @customer.last_name %><%= @customer.first_name %>さんの注文履歴一覧
  <% elsif params[:created_at] == "today" %>
    本日の注文履歴一覧
  <% else %>
    注文履歴一覧
  <% end %>
</h4>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>注文日</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>総計</th>
      <th>注文ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.created_at.strftime("%Y/%m%d %H:%M:%S"), admin_order_path(order), class: "underline" %></td>
        <td><%= link_to order.customer.customer_name, admin_customer_path(order.customer) %></td>
        <td><%= order.order_details.sum(:quantity) %></td>
        <td><%= order.billing_amount %>円</td>
        <td class="text-center"><%= order.order_status_i18n %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination d-flex justify-content-center mb-4">
  <%= paginate @orders %>
</div>
</section>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="title pt-4 ml-5 col-3">
      <h3 class="text-center bg-light">注文履歴詳細</h3>
    </div>
  </div>
  <div class="row">
    <table class="table table-borderless">
      <tr>
        <th class="col-3">購入者</th>
        <td class="col-9"><%=@order.customer.customer_name %></td>
      </tr>
      
      <tr>
        <th class="col-3">注文日</th>
        <td cladd="col-9"><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
      </tr>
      <tr>
        <th class="col-3">配送先</th>
        <td class="col-9"><%= @order.address1 %></td>
      </tr>
      <tr>
        <th class="col-3">支払方法</th>
        <td class="col-9"><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
        <th class="col-3">注文ステータス</th>
        <td class="col-9">
          <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
            <%= f.select :order_status, Order.order_statuses_i18n.invert %>
            <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="row">
    <div class="col-7">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @order_details.each do |order_detail| %>
              <%= form_with model: order_detail, url: admin_order_detail_path, method: :patch do |f| %>
                <td><%= order_detail.item.name %></td>
                <td><%= number_with_delimiter(order_detail.item.tax_price) %></td>
                <td><%= order_detail.quantity %></td>
                <td><%= number_with_delimiter(order_detail.total_price) %></td>
                <td><%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %></td>
                <td><%= f.submit "更新", class: "btn btn-success" %></td>
          </tr>
              <% end %>
            <% end %>
        </tbody>
      </table>
    </div>
    <div class="d-flex align-items-end col-5">
      <table class="tabel table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= number_with_delimiter(@product_total) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= number_with_delimiter(@order.postage) %>円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <th><%= number_with_delimiter(@order.billing_amount) %>円</th>
        </tr>
      </table>
    </div>
  </div>
</div>
    