config/routes.rb
Rails.application.routes.draw do
  #管理者用
  # URL /customers/sign_in...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
   get 'searches/search'

  namespace :admin do
   root to: "homes#top"
   get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
   resources :items, only: [:index, :show, :new, :create, :edit, :update]
   resources :genres, only: [:index, :edit, :create, :update]
   resources :orders, only: [:show, :update]
   resources :order_details, only: [:update]
   resources :customers, only: [:index, :show, :edit, :update]
  end

 #顧客用
  devise_for :customers, skip: [:password], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/quit' => 'customers#quit', as: 'confirm_quit'
    put 'customers/information' => 'customers#update'
    patch 'customers/out' => 'customers#out', as: 'out_customer'
    get 'about',to: 'homes#about'
    get '/genre/:id' =>'homes#index', as: 'index'
    resources :items, only: [:index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :orders, only:[:new, :index, :show, :create] do
      collection do
        post 'confirm'
        get 'thanks'
      end
    end
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end




  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :address, presence: true
  validates :pastal_code, presence: true,numericality: { only_integer: true }, length: { is: 7 }
  validates :name, presence: true
  
  # セレクトボタン内に1行でまとめて表示させるためのメソッド
  def address_display
    '〒' + pastal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  # 商品毎の小計を算出
  def subtotal
    item.tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy

  scope :only_active, -> { where(is_deleted: false) }


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :phone_number, presence: true, format: { with: /\A\d{10,11}\z/ }


  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  # 氏名をまとめたメソッド
  def customer_name
    last_name + first_name
  end

    def self.looks(search, word)
      @customers = Customer.where("first_name LIKE? OR last_name LIKE? OR first_name_kana LIKE? OR last_name_kana LIKE? OR phone_number LIKE? OR address LIKE? OR email LIKE?",
      "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%")
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
   validates :name, presence:true
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image

 enum is_selled: { sold_out: false, sale: true }
 has_many :cart_items, dependent: :destroy
 has_many :order_details, dependent: :destroy
 belongs_to :genre
 validates :name, presence: true
 validates :description, presence: true
 validates :image, presence: true
 validates :genre_id, presence: true
 validates :price, presence: true

 # 消費税を含む金額
 def tax_price
   (price * 1.1).floor
 end

 def get_image(width, height)
  image.variant(resize_to_limit: [width, height]).processed
 end
 
  def self.looks(search, word)
      @items = Item.where("name LIKE? OR description LIKE?", "%#{word}%", "%#{word}%")
  end


end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: {credit:0, bank: 1}
  enum order_status: {wait: 0, check: 1, making: 2, standby: 3, sent:4}

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postage, presence: true
  # セレクトボタン内に1行でまとめて表示させるメソッド
  def address_display
    '〒' + postal_code + ' '+ address1 + ' ' + name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { impossible: 0, stay: 1, making: 2, complete: 3 }

  belongs_to :order
  belongs_to :item

  # アイテム毎の小計を算出
  def total_price
    subprice.to_i * quantity.to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
     @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
     @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
  @item = Item.new(item_params)
   if @item.save
     flash[:success] = "商品を追加しました"
     redirect_to admin_item_path(@item)
   else
      render :new
   end
  end

  def edit
    @item= Item.find(params[:id])
  end

  def update
     @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "商品を編集しました"
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :image, :genre_id,:price,:is_selled)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  add_flash_types :success, :info, :warning, :danger

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
   def search
    @word = params[:word]
    # アドミン側と他で検索内容を変更
    if admin_signed_in?
    @customers = Customer.looks(params[:search], @word)
    else
    @items = Item.looks(params[:search], @word)
    end
   end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_alert(key)
    case key
    when "success"
      "success"
    when "danger"
      "danger"
    when "notice"
      "success"
    end 
  end 
        
        
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger" role="alert">
      <h5 class="alert-heading"><%= obj.errors.count %> 件のエラーが発生しました。</h5>
      <hr>
        <ul>
          <% obj.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, class: "alert alert-#{bootstrap_alert(key)}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-white text-dark pt-5 pb-4">
      <div class="container">
              <div class='row justify-content-center'>
                  <div class='mx-auto'>
                        <% if admin_signed_in? %>
                         <p> 管理者ログイン中...</p>
                          <% end %>
     
            <%= image_tag 'photo_1.png', size: '150x50' %>
            </div>
          </div>
　　　　　</div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/_header.html.erb
<header>
    <!--ナビゲーションメニュー-->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#c0c0c0;">
    <div class="container">
        <div class="row justify-content-center">
        <%= link_to root_path do %>
          <%= image_tag 'cake_icon.jpeg', size: '80x80' %>
        <% end %>
      </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">

        <!--会員ログイン後ヘッダー-->
        <% if customer_signed_in? %>
        <li class="nav-item">
            <%= link_to "マイページ",mypage_path, class: 'nav-link text-dark btn btn-light ml-5' %>
        </li>
        <li class="nav-item">
            <%= link_to "商品一覧", items_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "カート", cart_items_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "ログアウト",destroy_customer_session_path, method: :delete, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li>
        <div class="search_form serch_inner ml-2">
      <%= form_with url: searches_search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word, placeholder:"商品検索"%>
        <%= f.submit "検索",class: "btn btn-outline-light"  %>
      <% end %>
      </div>
      </li>
            <!--管理者ログイン後ヘッダー-->
        <% elsif admin_signed_in? %>
        <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark btn btn-light ml-5' %>
        </li>
        <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "ログアウト",destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li> <div class="search_form serch_inner ml-2">
      <%= form_with url: searches_search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word, placeholder:"顧客検索"%>
        <%= f.submit "検索",class: "btn btn-outline-light"  %>
      <% end %>
      </li>
            <% else %>
            <!--共通ログイン前ヘッダー-->
        <li class="nav-item">
            <%= link_to "About", about_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "商品一覧", items_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "ログイン",new_customer_session_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
        <li class="nav-item">
            <%= link_to "管理者ログイン",new_admin_session_path, class: 'nav-link text-dark btn btn-light ml-2' %>
        </li>
              <% end %>
              
              
        </ul>
        </nav>
        </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render partial: 'layouts/flash' %>
    <main>
    <%= yield %>
    </main>
     <%= render 'layouts/footer' %>
  </body>
  
</html>